LCC Assemble/Link/Interpret/Debug Ver 5.8  Mon Oct 02 11:48:51 2023
Jones, Erin, S

Header
o
Error on line 1 of i1.c:
// Erin JonesBad label

========================================== Program statistics
Input file name       =      i1.c
Instructions executed =    0 (hex)     0 (dec)
Program size          =    0 (hex)     0 (dec)
Max stack size        =    0 (hex)     0 (dec)
Load point            =    0 (hex)     0 (dec)
